

/**
 * Observer.java
 *
 * @author (your name) 
 * @version (a version number or a date)
 */


/**
 * 
 */

public interface Observer
{   
    public void update(Observable o);
}

/*
 *Source file generated by patternCoder for BlueJ Version 0.5.3.004.
 *For more info, please visit http://www.patterncoder.org.
 */