

/**
 * UnObserver.java
 *
 * @author (your name) 
 * @version (a version number or a date)
 */


/**
 *
 */

public class UnObserver implements Observer
{

    public void ConcreteObserver(){}
    
    public void update(Observable o){
        System.out.println("Updated "+this.toString()+" State = "+o.getState());
    }
}

/*
 *Source file generated by patternCoder for BlueJ Version 0.5.3.004.
 *For more info, please visit http://www.patterncoder.org.
 */